Refactoring and code cleanups
harveycabaguio/firefox-elementary-theme pull request #17
Opened 2018-06-24 21:58 UTC by rgiyf

"Soft" refactoring and code cleanups. There's more things to improve like moving more properties into variables and overall styles refactoring but I'm afraid I won't have time to work on this.

2018-06-26 03:26 UTC, harveycabaguio requested changes

2018-06-26 03:26 UTC, harveycabaguio commented on userChrome.css
> -  border-radius: 50% !important;
This is intentional, don't remove

2018-06-26 03:26 UTC, harveycabaguio commented on userChrome.css
> -  border: none !important;
brings back firefox's default back button look if removed

2018-06-26 03:26 UTC, harveycabaguio commented on userChrome.css
> -  background: none !important;
brings back firefox's default back button look if removed

2018-06-26 03:26 UTC, harveycabaguio commented on userChrome.css
> -#back-button:active > .toolbarbutton-icon {
needs to be here since firefox styles the back button differently, for the elementary style it needs to be the same.

2018-06-26 03:26 UTC, harveycabaguio commented on userChrome.css
> -  -moz-box-ordinal-group: 4; /*tabs on bottom*/
The order needs to be:
- navbar
- menubar
- bookmarksbar
- tabs

so all ordinal group values should be changed back

2018-06-26 03:26 UTC, harveycabaguio commented on userChrome.css
> +panel[type="arrow"][side="top"] {
this can be kept but the menupopup { } style made the context menus a bit closer to GTK theme

2018-06-26 08:12 UTC, rgiyf commented on userChrome.css
> -  border-radius: 50% !important;
I understand but it was a mess of different radius values for different buttons

2018-06-26 08:13 UTC, rgiyf commented
Hi! Could you please provide some screenshots if there're any issues caused by my refactoring?

2018-06-26 18:36 UTC, hiunnhue commented
here's the result: 

![image](https://user-images.githubusercontent.com/1015601/41932160-d1d15636-79b2-11e8-87aa-256db81c7524.png)

2018-06-26 20:28 UTC, rgiyf commented
Recent state:
![screenshot from 2018-06-26 23-27-09](https://user-images.githubusercontent.com/9195693/41937254-83576e10-7998-11e8-9db6-e12a78599170.png)
![screenshot from 2018-06-26 23-26-37](https://user-images.githubusercontent.com/9195693/41937263-84f7b554-7998-11e8-909e-12cd6f85de8a.png)

2018-06-27 15:57 UTC, hiunnhue commented
Menu button should have surrounding shadow on mouse-click, right ? 

![image](https://user-images.githubusercontent.com/1015601/41985408-cabdab84-7a65-11e8-9965-b8b995fe8fd6.png)

2018-06-28 16:38 UTC, hiunnhue commented
another minor issue: 

1. move the "New Tab" button to the left side of tab bar
2. keep clicking the "New Tab" button
3. you'll see the window close button moving up and down

2018-07-03 17:07 UTC, hiunnhue commented
The "show more bookmarks" button seems to have more padding on the right side: 

![image](https://user-images.githubusercontent.com/1015601/42234266-99b1891e-7f26-11e8-80f4-55ae6ac050d8.png)

2018-09-15 13:03 UTC, closed without merging